### ISSUE TITLE
Map covers are not greyed out when clicking on other map cover

### ISSUE THREAD

**Issue by dpayk** [conterra/mapapps-map-movie-template#1]
### Reproduction
- Use slider to crossfade between different maps. -> Only the currently visible map is shown as a clear image, all other maps have a sepia overlay.
- Click on maps to jump to other maps directly (not using the slider). -> The sepia effect is not set correctly.

**Comment by matthiasstein** [comment]
Fixed in https://github.com/conterra/mapapps-map-movie-template/releases/tag/v2.0.1
